apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: swegen-pipeline

resources:
  - deployment.yaml

configMapGenerator:
  - name: swegen-arc-gateway
    files:
      - swegen-arc-gateway.py
  - name: swegen-arc-litellm
    files:
      - config.yaml=litellm-config.yaml

generatorOptions:
  disableNameSuffixHash: true
